const courses = {
    "Block City 1": function () {
        // Set player position
        setPlayerPosition(0, 10, -15, 0);

        setSkyColor(0x87CEEB);

        // Ground
        World.addObstacle(0x808080, 80, -1, 0, 200, 1, 20, 0);
        World.addObstacle(0x808080, 0, 2, -15, 10, 1, 10, 0);

        // Obstacle
        World.addObstacle(0xff0000, 5, 0, 0, 2, 2, 2, 0);
        World.addObstacle(0xff0000, -5, 0, 0, 2, 2, 2, 0);

        World.addObstacle(0xff0000, 0, 0, 5, 2, 2, 2, 0);

        // Water
        // World.addWater(0x0000ff, 20, -1, 0, 20, 10, 20);

        // Lava
        World.addLava(0xff2F00, 19.5, -1, 0, 21, 10, 21);

        velocity.y = 10;
        paused = false;
        
        playMusic("blockCity");
    },

    // These course were generated by AI
    "AI City 1": function () {
        // Set player position
        setPlayerPosition(0, 5, -15, 0);

        setSkyColor(0x87CEEB);

        // Starting platform
        World.addObstacle(0x808080, 0, 2, -15, 10, 1, 10, 0);

        // First section - jumping platforms
        World.addObstacle(0x808080, 8, 3, -12, 4, 1, 4, 0.2);
        World.addObstacle(0x808080, 16, 4, -8, 4, 1, 4, -0.2);
        World.addObstacle(0x808080, 24, 5, -4, 4, 1, 4, 0);        // Water section with platforms
        World.addWater(0x0000ff, 32, 0, 0, 20, 10, 20);
        World.addObstacle(0x808080, 32, 3, 0, 3, 1, 3, 0);
        World.addObstacle(0x808080, 38, 3, 0, 3, 1, 3, 0);
        World.addObstacle(0x808080, 44, 3, 0, 3, 1, 3, 0);

        // Challenging stepping stone section with lava
        World.addObstacle(0x808080, 49, 3.5, 0, 1.5, 0.5, 1.5, 0.2);
        World.addObstacle(0x808080, 52, 4.5, 0, 1.5, 0.5, 1.5, -0.1);
        World.addObstacle(0x808080, 55, 6, 0, 8, 1, 8, 0);
        World.addLava(0xff2F00, 55, 0, 0, 8, 5, 8);

        // Moving forward - higher platforms with water sections
        World.addObstacle(0x808080, 65, 8, 5, 4, 1, 4, 0.3);
        World.addWater(0x0000ff, 69, 0, 7, 8, 12, 8);
        World.addObstacle(0x808080, 73, 10, 10, 4, 1, 4, -0.3);
        World.addObstacle(0x808080, 81, 12, 15, 4, 1, 4, 0);

        // Spiral ascent platforms
        World.addObstacle(0x808080, 85, 13, 15, 3, 1, 3, 0.2);
        World.addObstacle(0x808080, 88, 14, 18, 3, 1, 3, 0.4);
        World.addObstacle(0x808080, 85, 15, 21, 3, 1, 3, -0.3);
        World.addObstacle(0x808080, 82, 16, 18, 3, 1, 3, -0.1);

        // Lava challenge section
        World.addLava(0xff2F00, 81, 0, 25, 20, 11, 10);
        World.addObstacle(0x808080, 81, 7, 25, 2, 1, 2, 0);
        World.addObstacle(0x808080, 85, 7, 25, 2, 1, 2, 0);
        World.addObstacle(0x808080, 89, 7, 25, 2, 1, 2, 0);

        // Advanced stepping stones
        World.addObstacle(0x808080, 89, 9, 27, 2, 1, 2, 0.1);
        World.addObstacle(0x808080, 91, 10.5, 28, 2, 1, 2, -0.1);
        World.addObstacle(0x808080, 93, 12, 29, 2, 1, 2, 0.2);
        
        // Moving platform section
        World.addObstacle(0x808080, 95, 13, 32, 3, 1, 3, 0.3);
        World.addObstacle(0x808080, 99, 14, 35, 3, 1, 3, -0.2);
        World.addObstacle(0x808080, 103, 15, 38, 3, 1, 3, 0.1);
        
        // Water and platform maze
        World.addWater(0x0000ff, 107, 0, 38, 15, 18, 15);
        World.addObstacle(0x808080, 107, 8, 38, 2, 1, 2, 0);
        World.addObstacle(0x808080, 111, 10, 40, 2, 1, 2, 0.2);
        World.addObstacle(0x808080, 115, 12, 42, 2, 1, 2, -0.2);

        // Final challenge section
        World.addLava(0xff2F00, 130, 2, 42, 10, 15, 10);
        World.addObstacle(0x808080, 130, 16, 42, 10, 1, 10, 0);

        // Victory platform
        World.addObstacle(0x808080, 121, 13, 42, 4, 1, 4, 0);

        // Decorative obstacles
        World.addObstacle(0xff0000, 8, 4, -12, 1, 2, 1, 0.4);
        World.addObstacle(0xff0000, 24, 6, -4, 1, 2, 1, 0.2);
        World.addObstacle(0xff0000, 65, 9, 5, 1, 2, 1, 0.3);
        World.addObstacle(0xff0000, 85, 14, 15, 1, 2, 1, 0.2);
        World.addObstacle(0xff0000, 103, 16, 38, 1, 2, 1, 0.4);
        World.addObstacle(0xff0000, 130, 19, 42, 2, 2, 2, 0.5);

        velocity.y = 10;
        paused = false;
        
        playMusic("blockCity");
    },

    "AI Tower 1": function () {
        // Set player position
        setPlayerPosition(0, 5, 0, 0);

        setSkyColor(0x222222);

        // Base platform
        World.addObstacle(0x808080, 0, 2, 0, 20, 1, 20, 0);

        // Tower structure - using dark colors for ominous feel
        const towerHeight = 200; // Really tall tower
        const segments = 20;
        const heightPerSegment = towerHeight / segments;

        // Create tower segments
        for(let i = 0; i < segments; i++) {
            const y = i * heightPerSegment + 3; // Start at y=3 to account for base platform
            
            // Main corner pillars (4 corners, thin to not block view)
            World.addObstacle(0x404040, -8, y, -8, 2, heightPerSegment, 2, 0);
            World.addObstacle(0x404040, 8, y, -8, 2, heightPerSegment, 2, 0);
            World.addObstacle(0x404040, -8, y, 8, 2, heightPerSegment, 2, 0);
            World.addObstacle(0x404040, 8, y, 8, 2, heightPerSegment, 2, 0);

            // Platforms with different patterns per segment
            switch(i % 4) {
                case 0: // Spiral pattern
                    World.addObstacle(0x505050, -5, y+2, -5, 6, 1, 6, 0.2);
                    World.addObstacle(0x505050, 5, y+4, 0, 6, 1, 6, -0.2);
                    World.addObstacle(0x505050, -5, y+6, 5, 6, 1, 6, 0.2);
                    break;
                
                case 1: // Cross pattern
                    World.addObstacle(0x505050, 0, y+2, 0, 12, 1, 3, 0);
                    World.addObstacle(0x505050, 0, y+4, 0, 3, 1, 12, 0);
                    break;
                
                case 2: // Corner jumps
                    World.addObstacle(0x505050, -5, y+2, -5, 4, 1, 4, 0.4);
                    World.addObstacle(0x505050, 5, y+4, 5, 4, 1, 4, -0.4);
                    World.addObstacle(0x505050, -5, y+6, 5, 4, 1, 4, 0.4);
                    World.addObstacle(0x505050, 5, y+8, -5, 4, 1, 4, -0.4);
                    break;
                
                case 3: // Challenge section with water and lava
                    World.addWater(0x000088, 0, y, 0, 12, 4, 12);
                    World.addObstacle(0x505050, 0, y+2, 0, 3, 1, 3, 0.2);
                    World.addObstacle(0x505050, 5, y+4, 5, 3, 1, 3, -0.2);
                    World.addObstacle(0x505050, -5, y+6, -5, 3, 1, 3, 0.2);
                    World.addLava(0xff2F00, 0, y+8, 0, 4, 1, 4);
                    World.addObstacle(0x505050, 0, y+8, 0, 2, 1.5, 2, 0);

                    break;
            }
        }        // Victory platform at the top
        World.addObstacle(0xFFD700, -20, towerHeight + 3, 0, 20, 1, 20, 0);
        // Victory decoration
        World.addObstacle(0xFFA500, -20, towerHeight + 5, 0, 6, 6, 6, 0.4);
        // Victory collectible
        World.addCollectible(-20, towerHeight + 12, 0, true);

        velocity.y = 10;
        paused = false;
        
        playMusic("enemyTowers");
    },

    "": function () {
        // All yours, GitHub!
    },

    "Golden Summit": function () {
        // Set player position
        setPlayerPosition(0, 5, -15, 0);

        setSkyColor(0x1E90FF); // Deep blue sky

        // Starting platform
        World.addObstacle(0x808080, 0, 2, -15, 12, 1, 12, 0);

        // Section 1: The Valley
        // Create a valley with alternating platforms
        for(let i = 0; i < 5; i++) {
            const x = 15 + (i * 12);
            World.addObstacle(0x808080, x, 3 + (i * 1.5), -15 + (i * 3), 4, 1, 4, 0.2);
            World.addObstacle(0x808080, x + 6, 4 + (i * 1.5), -12 + (i * 3), 4, 1, 4, -0.2);
        }

        // Section 2: The Water Challenge
        World.addWater(0x0000ff, 75, 0, 0, 30, 15, 30);
        // Floating platforms above water
        for(let i = 0; i < 4; i++) {
            for(let j = 0; j < 4; j++) {
                if((i + j) % 2 === 0) {
                    World.addObstacle(0x808080, 65 + (i * 8), 8, -10 + (j * 8), 3, 1, 3, 0.3);
                }
            }
        }

        // Section 3: The Lava Climb
        World.addLava(0xff2F00, 120, 0, 0, 40, 20, 40);
        // Create ascending platforms over lava
        for(let i = 0; i < 8; i++) {
            const height = 10 + (i * 3);
            World.addObstacle(0x808080, 110 + (i * 5), height, (i * 4), 3, 1, 3, (i % 2 === 0 ? 0.2 : -0.2));
        }

        // Section 4: The Sky Bridge
        const bridgeHeight = 35;
        for(let i = 0; i < 6; i++) {
            World.addObstacle(0x808080, 150 + (i * 8), bridgeHeight, 30, 3, 1, 3, 0);
            if(i < 5) { // Gaps between platforms
                World.addWater(0x0000ff, 153 + (i * 8), bridgeHeight - 20, 30, 5, 20, 5);
            }
        }

        // Section 5: The Final Challenge
        // Moving platforms in spiral pattern
        for(let i = 0; i < 4; i++) {
            const angle = i * (Math.PI / 2);
            World.addObstacle(0x808080, 
                200 + Math.cos(angle) * 8, 
                bridgeHeight + 5 + (i * 2), 
                30 + Math.sin(angle) * 8, 
                3, 1, 3, 0.3);
        }

        // Victory Platform with Gold Block
        World.addObstacle(0xFFD700, 220, bridgeHeight + 15, 30, 15, 1, 15, 0);
        
        // Add decorative obstacles
        World.addObstacle(0xff0000, 220, bridgeHeight + 17, 30, 2, 4, 2, 0.4);
        
        // Add the Gold Block Collectible
        World.addCollectible(220, bridgeHeight + 20, 30, true);

        // Victory arch
        World.addObstacle(0xFFA500, 220, bridgeHeight + 16, 25, 1, 8, 1, 0);
        World.addObstacle(0xFFA500, 220, bridgeHeight + 20, 27.5, 1, 1, 5, 0);
        World.addObstacle(0xFFA500, 220, bridgeHeight + 16, 30, 1, 8, 1, 0);

        velocity.y = 10;
        paused = false;
        
        playMusic("blockCity");
    },
}